ABCDLKF;SDNFDSBFSDKLFDSGFNDSLKGMDSAKLGNSADG
4SDGFNKDSAFGDSAGLS4LK4SDGKDSG;KLDSF
SADFLKDSNGFN
dev server---->sit server --->uat server--->production


versioning tool--- GIT


CLIENT REQUIREMENT:(CHANGE REQUEST)
      CHANGES   -- 1ST VERSION
       
       SOME CHANGES  -- 2ND VERSION
       
       SOME MORE CHANGES   --3RD VERSION
       
       
1>CLONE
2>ADD
3>COMMIT
4>PUSH

SDFKDSFKDSGFKJ
LOCAL SERVER--->STAGING AREA--->GLOBAL SERVER


SOURCE TREE